### ISSUE TITLE
Mark homework 2 of Xuchun Liu

### ISSUE THREAD

**Issue by xuchun725** [xuchun725/stat679work#3]
Hi professor @cecileane 

I submitted my homework 2. 
Here is the [latest version](https://github.com/xuchun725/stat679work/commit/3f8cccf2a06cca541648971f0850ed4956e45feb) and here is the [hw2](https://github.com/xuchun725/stat679work/tree/master/hw2) folder in repo stat679work.

Best, 
Xuchun

**Comment by cecileane** [comment]
Hi Xuchun,

Very nice job! Your work was easy to go through, and your script worked. More details below.

## overall presentation

In general, it's good to get into the habit of separating the scripts and input/output files into different directories.
It's great that you documented the version of Python used to develop your script. You also made great use of markdown style, even in your github issue where you had a very convenient link to your hw2 folder. Your list of features and assumptions (checked) is also great, and your section explaining how to use the script is very detailed: very easy to understand.

I love that you explain how to get help on your module, with a docstring that lists the arguments, assumptions and output.

## running your script

It worked very easily! You give 2 columns for the energy values, one rescaled by 1000 and one not, but the header lines explain and give the correct units.
The only glitch was that the header is re-written when the output is appended to an existing file, like this:

    $ ./merge.py -t waterTemperature.csv -e energy.csv -o myout.csv
    $ ./merge.py -t waterTemperature.csv -e energy.csv -o myout.csv --append
    $ grep -A 2 -B 2 "#" myout.csv
    #,Date Time (GMT-05:00),Temperature,Energy Produced(Wh),Energy Produced(kWh)
    1,2016-07-29 10:26:34,72.86,,
    2,2016-07-29 11:26:34,73.92,,
    --
    --
    362,2016-08-13 11:26:34,73.06,,
    363,2016-08-13 12:26:34,76.39,,
    #,Date Time (GMT-05:00),Temperature,Energy Produced(Wh),Energy Produced(kWh)
    1,2016-07-29 10:26:34,72.86,,
    2,2016-07-29 11:26:34,73.92,,

So this extra header will get in the way for follow-up analyses.

## about your code

Great work to make your script work either as a command-line script, or a module to re-use the functions within python. Great work using the argparse and time modules, too.

On line 49, you hard-coded the assumption that the temparature file has 2 lines for its header: `lines = [line.rstrip() for line in temp if line != '\n'][2:]`. It would have been good to document this assumption in your readme file (and/or in your docstring).

You have a good use of `assert` statements to check assumptions and return helpful error messages, and great use of list comprehension!

Unfortunately, the output is sent to STDERR instead of STDOUT if no output file name is given, because of line 94: `sys.stderr.write(out)`. It will look like your script has a bad exit status, and pipelines would not get the output if the user separates the STDERR from the STDOUT.

Finally, you could have broken your work into separate smaller functions.

Great job overall.

**Comment by cecileane** [comment]
Hi Xuchun,
I would like to send your script to the person who provided the data --and who could use your script in the future. So I just made changes and pushed them to your repository, to fix the 2 small things that I talked about above: 

1. I added things to your readme file about assumption on the headers/last line of the data files, also comments about this in the code

2. I changed `stderr` to `stdout` on line 94.

You can see the details of my changes here: https://github.com/xuchun725/stat679work/commit/cfe11a27c809ea8f7a64cd74172b053d5500c3c3 (I could make these changes because you had added me as collaborator earlier in the semester).

Thanks for your great work!

**Comment by xuchun725** [comment]
Hi professor @cecileane ,

I'm so happy and excited that my scripts could help!
This hw is really a good learning experience and thank you for your correction! 

Xuchun
